#############################
#              __
#  ____  _____/ /_  __________
# /_  / / ___/ __ \/ ___/ ___/
#  / /_(__  ) / / / /  / /__
# /___/____/_/ /_/_/   \___/
##############################

bindkey -v
bindkey "^R" history-incremental-search-backward

export DOT_DIR=~/dotfiles

# PATH
export PATH=/opt/homebrew/bin:$PATH
export PATH="$HOME/.local/bin:$PATH"

# Env
export EDITOR=nvim
export XDG_CONFIG_HOME="$HOME/.config"
export CONFIG_DIR="$HOME/.config"
export TZ="Europe/Belgrade"
export LG_CONFIG_FILE="$HOME/.config/lazygit/config.yml"

if [[ -t 0 ]]; then
  source $DOT_DIR/zsh/aliases.zsh
  source $DOT_DIR/zsh/prompt.zsh

  source ~/.zsh_plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh

  [[ -f ~/.zsh_plugins/zsh-kubectl-prompt/zsh-kubectl-prompt.plugin.zsh ]] && \
    source ~/.zsh_plugins/zsh-kubectl-prompt/zsh-kubectl-prompt.plugin.zsh

  neofetch
fi

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# Machine-specific config (not committed to repo)
[ -f "$HOME/.zshrc.local" ] && source "$HOME/.zshrc.local"
